name: puzzle_hack
description: Puzzle Hack
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  gap: ^2.0.0
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  just_audio: ^0.9.18
  url_launcher: ^6.0.17
  rive: ^0.8.1
  flutter_svg: ^1.0.3

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/rive/
    - assets/sakura/
    - assets/logo/
    - assets/audio/
    - assets/icons/